version: '3.3'

services:
  site_adc:
    build: .
    container_name: site_adc
    restart: unless-stopped
    volumes:
      - .:/var/www/html/
    user: 1000:1000
    ports:
      - 8080:80
    depends_on:
      - site_adc_mysql
    env_file:
      - .env

  site_adc_mysql:
    image: mysql:8.0
    container_name: site_adc_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${BD_BASE}
      MYSQL_ROOT_PASSWORD: ${BD_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: site_adc_phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: ${BD_HOST}
      PMA_USER: ${BD_USER}
      PMA_PASSWORD: ${BD_PASSWORD}
    depends_on:
      - site_adc_mysql
    env_file:
      - .env

volumes:
  db_data: