version: '3.3'

services:
  site_adc:
    build: .
    container_name: site_adc
    restart: unless-stopped
    volumes:
      - .:/var/www/html/
    user: 1000:1000
    ports:
      - 8080:80
    depends_on:
      - site_adc_mysql

  site_adc_mysql:
    image: mysql:8.0
    container_name: site_adc_mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: nfa021ProjetV2
      # MYSQL_ROOT_PASSWORD: ''
      # MYSQL_USER: test
      # MYSQL_PASSWORD: ''
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: site_adc_phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: site_adc_mysql
      PMA_USER: root
      PMA_PASSWORD: ''
    depends_on:
      - site_adc_mysql

volumes:
  db_data: