-- MySQL Script generated by MySQL Workbench
-- Tue Jun 15 23:04:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nfa021Projet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nfa021Projet` ;

-- -----------------------------------------------------
-- Schema nfa021Projet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nfa021Projet` DEFAULT CHARACTER SET utf8 ;
USE `nfa021Projet` ;

-- -----------------------------------------------------
-- Table `nfa021Projet`.`VILLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nfa021Projet`.`VILLE` ;

CREATE TABLE IF NOT EXISTS `nfa021Projet`.`VILLE` (
  `idVille` INT NOT NULL AUTO_INCREMENT,
  `cp` VARCHAR(5) NOT NULL,
  `nomVille` VARCHAR(75) NOT NULL,
  `departement` VARCHAR(50) NOT NULL,
  `region` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idVille`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nfa021Projet`.`CLIENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nfa021Projet`.`CLIENT` ;

CREATE TABLE IF NOT EXISTS `nfa021Projet`.`CLIENT` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NOT NULL,
  `prenom` VARCHAR(150) NOT NULL,
  `adresse` VARCHAR(150) NOT NULL,
  `telephone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `profilAdmin` TINYINT NULL,
  `estValide` INT NULL,
  `jetonValidation` VARCHAR(255) NULL,
  `fkIdVille` INT NOT NULL,
  PRIMARY KEY (`idClient`, `fkIdVille`),
  CONSTRAINT `CLIENT_fkIdVille`
    FOREIGN KEY (`fkIdVille`)
    REFERENCES `nfa021Projet`.`VILLE` (`idVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX_CLIENT_VILLE_fkIdVille` ON `nfa021Projet`.`CLIENT` (`fkIdVille` ASC);


-- -----------------------------------------------------
-- Table `nfa021Projet`.`INSTRUMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nfa021Projet`.`INSTRUMENT` ;

CREATE TABLE IF NOT EXISTS `nfa021Projet`.`INSTRUMENT` (
  `idInstrument` INT NOT NULL AUTO_INCREMENT,
  `typeInstrument` VARCHAR(150) NOT NULL,
  `marque` VARCHAR(50) NOT NULL,
  `modele` VARCHAR(50) NOT NULL,
  `numeroSerie` VARCHAR(50) NOT NULL,
  `dateAchat` DATE NOT NULL,
  `fkIdClient` INT NOT NULL,
  PRIMARY KEY (`idInstrument`, `fkIdClient`),
  CONSTRAINT `INSTRUMENT_fkIdClient`
    FOREIGN KEY (`fkIdClient`)
    REFERENCES `nfa021Projet`.`CLIENT` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX_INSTRUMENT_CLIENT_fkIdClient` ON `nfa021Projet`.`INSTRUMENT` (`fkIdClient` ASC);


-- -----------------------------------------------------
-- Table `nfa021Projet`.`ENTRETIEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nfa021Projet`.`ENTRETIEN` ;

CREATE TABLE IF NOT EXISTS `nfa021Projet`.`ENTRETIEN` (
  `idEntretien` INT NOT NULL AUTO_INCREMENT,
  `dateEntretien` DATE NOT NULL,
  `descriptionEntretien` LONGTEXT NOT NULL,
  `prixEntretien` DOUBLE NOT NULL,
  `fkIdInstrument` INT NOT NULL,
  PRIMARY KEY (`idEntretien`, `fkIdInstrument`),
  CONSTRAINT `ENTRETIEN_fkIdInstrument`
    FOREIGN KEY (`fkIdInstrument`)
    REFERENCES `nfa021Projet`.`INSTRUMENT` (`idInstrument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX_ENTRETIEN_INSTRUMENT_fkIdInstrument` ON `nfa021Projet`.`ENTRETIEN` (`fkIdInstrument` ASC);


-- -----------------------------------------------------
-- Table `nfa021Projet`.`INSTRUMENT_LOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nfa021Projet`.`INSTRUMENT_LOCATION` ;

CREATE TABLE IF NOT EXISTS `nfa021Projet`.`INSTRUMENT_LOCATION` (
  `idInstruLoc` INT NOT NULL AUTO_INCREMENT,
  `typeInstruLoc` VARCHAR(50) NOT NULL,
  `marqueInstruLoc` VARCHAR(50) NOT NULL,
  `modeleInstruLoc` VARCHAR(50) NOT NULL,
  `numeroSerieInstruLoc` VARCHAR(50) NOT NULL,
  `dateAchatInstruLoc` DATE NOT NULL,
  PRIMARY KEY (`idInstruLoc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nfa021Projet`.`FORFAIT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nfa021Projet`.`FORFAIT` ;

CREATE TABLE IF NOT EXISTS `nfa021Projet`.`FORFAIT` (
  `idForfait` INT NOT NULL AUTO_INCREMENT,
  `duree` VARCHAR(45) NOT NULL,
  `tarif` DOUBLE NOT NULL,
  PRIMARY KEY (`idForfait`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nfa021Projet`.`LOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nfa021Projet`.`LOCATION` ;

CREATE TABLE IF NOT EXISTS `nfa021Projet`.`LOCATION` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `dateLocation` DATE NOT NULL,
  `finLocation` DATE NOT NULL,
  `fkIdInstruLoc` INT NOT NULL,
  `fkIdForfait` INT NOT NULL,
  `fkIdClient` INT NOT NULL,
  PRIMARY KEY (`idLocation`, `fkIdInstruLoc`, `fkIdForfait`, `fkIdClient`),
  CONSTRAINT `LOCATION_fkIdInstruLoc`
    FOREIGN KEY (`fkIdInstruLoc`)
    REFERENCES `nfa021Projet`.`INSTRUMENT_LOCATION` (`idInstruLoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LOCATION_fkIdForfait`
    FOREIGN KEY (`fkIdForfait`)
    REFERENCES `nfa021Projet`.`FORFAIT` (`idForfait`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LOCATION_fkIdClient`
    FOREIGN KEY (`fkIdClient`)
    REFERENCES `nfa021Projet`.`CLIENT` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX_LOCATION_INSTRUMENT_LOCATION_fkIdInstruLoc` ON `nfa021Projet`.`LOCATION` (`fkIdInstruLoc` ASC);

CREATE INDEX `IDX_LOCATION_FORFAIT_fkIdForfait` ON `nfa021Projet`.`LOCATION` (`fkIdForfait` ASC);

CREATE INDEX `fkIdLOCATION1_idx` ON `nfa021Projet`.`LOCATION` (`fkIdClient` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
